spring:
  datasource:
    url: jdbc:postgresql://165.227.192.124:5432/wasteDB
    username: postgres
    password: Asante=0198

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true

  flyway:
    baselineOnMigrate: false
    user: postgres
    password: kwamepass
    url: jdbc:postgresql://localhost:5432/wasteDB
    table: flyway_schema_history
    enabled: false

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 29400