POST http://localhost:8080/api/v1/bin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrd2FtZWtlcnQiLCJpYXQiOjE2MzAzMTkyMjAsImV4cCI6MTYzMDM0ODYyMH0.KRxQYEw1wfbXPcQdJP-Nw5Cs0N0o-zzDn0OSqP9TXblF6-M7g3qT2IaLtYyaMW9Qxk0wGMIeSexYAZxXoKM1kA


{
  "latitude": 5.234323,
  "longitude": 6.234323,
  "contactName": "kwamekert",
  "contactPhone": "0244996545",
  "contactAddress": "Mamprobi"
}

###
PUT http://localhost:8080/api/v1/bin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrd2FtZWtlcnQiLCJpYXQiOjE2MzAzMTkyMjAsImV4cCI6MTYzMDM0ODYyMH0.KRxQYEw1wfbXPcQdJP-Nw5Cs0N0o-zzDn0OSqP9TXblF6-M7g3qT2IaLtYyaMW9Qxk0wGMIeSexYAZxXoKM1kA


{
  "id": 1,
  "latitude": 5.234323,
  "longitude": 6.234323,
  "contactName": "dennis",
  "contactPhone": "0244996545",
  "contactAddress": "Mamprobi"
}

###

GET http://localhost:8080/api/v1/bin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrd2FtZWtlcnQiLCJpYXQiOjE2MzAzMTkyMjAsImV4cCI6MTYzMDM0ODYyMH0.KRxQYEw1wfbXPcQdJP-Nw5Cs0N0o-zzDn0OSqP9TXblF6-M7g3qT2IaLtYyaMW9Qxk0wGMIeSexYAZxXoKM1kA

###
GET http://localhost:8080/api/v1/bin/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrd2FtZWtlcnQiLCJpYXQiOjE2MzAzMTkyMjAsImV4cCI6MTYzMDM0ODYyMH0.KRxQYEw1wfbXPcQdJP-Nw5Cs0N0o-zzDn0OSqP9TXblF6-M7g3qT2IaLtYyaMW9Qxk0wGMIeSexYAZxXoKM1kA

###

